version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd nodejs-cicd-poc
      - cd client
      - npm install

  build:
    commands:
      - npm run build
      - cd ../server
      - npm install

artifacts:
  files:
    - nodejs-cicd-poc/server/**/*
    - nodejs-cicd-poc/client/dist/**/*
    - nodejs-cicd-poc/appspec.yml
    - nodejs-cicd-poc/scripts/**/*
